name: "dousheng"
mode: "dev"
port: 8080
version: "v0.0.1"
start_time: "2022-06-09"
machine_id: 1

auth:
  jwt_expire: 8760

log:
  level: "debug"
  filename: "./log/douyin.log"
  max_size: 1000
  max_age: 3600
  max_backups: 5

mysql:
  host: "127.0.0.1"
  port: 3306
  user: "root"
  password: "abc123"
  dbname: "douyins"
  max_open_conns: 200
  max_idle_conns: 50

redis:
  host: "127.0.0.1"
  port: 6379
  password:
  db: 0
  pool_size: 100